apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockvote-server-side
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockvote-server-side
  template:
    metadata:
      labels:
        app: blockvote-server-side
    spec:
      containers:
      - name: blockvote-server-side
        image: kingdavid678/blockvote-server-side:latest
        ports:
        - containerPort: 8080  # Adjust port as needed
        envFrom:
        - secretRef:
            name: blockvote-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: blockvote-server-side
spec:
  selector:
    app: blockvote-server-side
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer  # Change this to NodePort if LoadBalancer is not available
